name: Docker scan

on:
  workflow_call:
    inputs:
      buildContext:
        description: "docker build context"
        default: "."
        required: false
        type: string

jobs:
  docker-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build an image from Dockerfile
        run: docker build -t ${{ github.repository }}:${{ github.sha }} ${{ inputs.buildContext }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.14.0
        with:
          image-ref: "${{ github.repository }}:${{ github.sha }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
