name: Build helm charts and push to gcp

on:
  workflow_call:
    inputs:
      chartPath:
        description: "helm Chart.yaml path e.g. charts/yourapp/Chart.yaml"
        required: true
        type: string
      gcpDestination:
        description: "gcp directory where the packaged chart will be uploaded"
        required: true
        type: string
    secrets:
      GCP_CREDENTIALS:
        description: "gcp credentials"
        required: true

jobs:
  gcp-helm-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.0

      - name: Package Helm Chart
        run: helm package ./charts/* --destination ./charts

      - name: Push chart to GCP Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v0.10.4
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          path: ./charts
          glob: "*.tgz"
          destination: ${{ inputs.gcpDestination }}
          parent: false
