name: Build helm charts and push to gcp

on:
  workflow_call:
    inputs:
      chartsPath:
        description: "path chart files (including glob pattern)"
        required: false
        default: "./charts/*"
        type: string
      gcpDestination:
        description: "gcp directory where the packaged chart will be uploaded"
        required: true
        type: string
      runsOn:
        description: "github actions runner to use for this action"
        default: "ubuntu-latest"
        required: false
        type: string
    secrets:
      GCP_CREDENTIALS:
        description: "gcp credentials"
        required: true

jobs:
  gcp-helm-charts:
    runs-on: ${{ inputs.runsOn }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Helm tool installer
        uses: Azure/setup-helm@v4.2.0

      - name: Package Helm Chart
        run: helm package ${{ inputs.chartsPath }} --destination ./charts

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.10
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Push chart to GCP Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v2.1.0
        with:
          path: ./charts
          glob: "*.tgz"
          process_gcloudignore: false
          destination: ${{ inputs.gcpDestination }}
          parent: false
